env:
  browser: true
  es2021: true
extends:
  - plugin:react/recommended
  - standard
  - next/core-web-vitals
  - prettier
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules:
  react/jsx-filename-extension: off
  react/jsx-props-no-spreading: off
settings:
  import/resolver:
    typescript:
      project: jsconfig.json
