extends:
  - airbnb
  - next/core-web-vitals
  - prettier
rules:
  react/function-component-definition:
    - error
    - namedComponents: function-declaration
  react/jsx-filename-extension: off
  react/jsx-props-no-spreading: off
settings:
  import/resolver:
    typescript:
      project: jsconfig.json
